# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/webhook_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.retries=3
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.batch.size=65536
spring.kafka.producer.properties.partitioner.class=org.apache.kafka.clients.producer.RoundRobinPartitioner

# Kafka topic
kafka.topic.name=webhook-events
kafka.topic.replication-factor=1

# Redis
spring.redis.host=localhost
spring.redis.port=6379

# Event generator config
generator.batch-size=500

generator.accounts[0].id=dddddddd-0001-0001-0001-000000000001
generator.accounts[0].event-count=20000

generator.accounts[1].id=dddddddd-0002-0002-0002-000000000002
generator.accounts[1].event-count=200

generator.accounts[2].id=dddddddd-0003-0003-0003-000000000003
generator.accounts[2].event-count=5

# Logging
logging.level.com.example.webhookgenerator=INFO
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
